### ISSUE TITLE
Save the audio after setting equalizer levels?

### ISSUE THREAD

**Issue by Zeit42** [osamabinomar/AndroidEqualizer#13] opened 2020-03-11 06:05 UTC
First of all, this app is amazing. But I'm wondering how I'll be able to save the audio after I adjust the equalizer levels. Do you know how to and can you share? Thank you.

**Comment by bullheadandplato** [comment] 2021-02-06 18:54
duplicate of #10

**Closed as completed by bullheadandplato** 2021-02-06 18:54 UTC
